# Generated by Django 5.1.2 on 2024-10-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_weatherdata_ldr_value_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherData',
            new_name='TemperatureHumidityData',
        ),
    ]
