# Generated by Django 5.1.2 on 2024-10-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_weatherdata_temperaturehumiditydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarRadiationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('solar_radiation', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
