# Generated by Django 5.1.2 on 2024-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solarradiationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.FloatField()),
                ('rain_intensity', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
